services:
  mysql:
    build: .
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "9999:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
